### ISSUE TITLE
Zero TTL Not Working

### ISSUE THREAD

**Issue by renegadeHomie** [web-push-libs/web-push#491] opened 2019-08-08 13:42 UTC
According to the spec [here](https://tools.ietf.org/html/draft-ietf-webpush-protocol-12#section-5.2), a zero TTL means that the message is not stored by FCM and only delivered to endpoints that are online at that moment.

In my testing using the node web-push library, when I am setting TTL to ZERO in the options object as follows :
`const options = {
        gcmAPIKey: <api_key>,
        vapidDetails: {
            subject: 'mailto:example@web-push-node.org',
            publicKey: <public_key>,
            privateKey: <private_key>
        },
        TTL: 0
}`

But receiving the web-push even after keeping the device offline for half hour.

Tested for both latest Chrome and Firefox.

Please help!

**Comment by marco-c** [comment] 2019-08-08 16:59
Duplicate of #284.

**Closed** 2019-09-04 08:51 UTC
