### ISSUE TITLE
Error code from GCM

### ISSUE THREAD

**Issue by nikhil32** [web-push-libs/web-push#328] opened 2018-05-16 13:53 UTC
We are using version 2.2.0 of this library. Whatever I am mentioning is not an issue with this library, but I cannot able to find references to the status code. We are still on GCM, not migrated to FCM.

We are getting following 4 error codes, can someone help us understand the exact meaning of this error codes or point to a right place.
NotRegistered(410)
Gone (410) 
InvalidTokenFormat(400) 
UnauthorizedRegistration(400) 

Sorry for posting in a wrong place.

**Comment by froodian** [comment] 2018-05-16 15:34
https://web-push-book.gauntface.com/chapter-04/02-web-push-protocol/#response-from-push-service has some info on response codes.

In my experience, 400 is often an invalid sender id in the manifest.json (or the sender id in there is valid but mismatched with the server api key used to send), or a failure to provide the VAPID credentials when sending (if you're using VAPID, and not using manifest.json).

410 is a "vanilla bounce" an is usually caused by the user removing push permission. The push services also reserve the right to expire subscriptions on their own, causing 410s.

**Comment by marco-c** [comment] 2018-06-16 07:10
Closing since it's not an issue with the library and I guess the question has been answered.

**Closed** 2018-06-16 07:10 UTC
